cmake_minimum_required(VERSION 3.10)
project(proc_killer)
set(CMAKE_CXX_STANDARD 17)
add_executable(killer killer.cpp)
if(WIN32)
    target_link_libraries(killer PRIVATE kernel32 user32)
    target_compile_definitions(killer PRIVATE UNICODE _UNICODE)
endif()
add_executable(user user.cpp)
if(WIN32)
    target_link_libraries(user PRIVATE kernel32 user32)
    target_compile_definitions(user PRIVATE UNICODE _UNICODE)
endif()
